name: go test
on: [push]

jobs:
  go-test:
    container:
      image: golang:1.13.0-alpine3.10
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: "setup"
        run: |
          apk --update add figlet
          go version | figlet
      - name: go test
        run: |
          cd ${GITHUB_WORKSPACE}
          go test -v -cover
